In [2]:
import numpy as np
import pandas as pd

df=pd.read_csv("../../data/raw/madden21_ratings.csv")
df.head()

,Team,Full Name,Overall Rating,Position,Age,Speed,Acceleration,Awareness,Agility,Strength,...,Jersey Number,Total Salary,Signing Bonus,Archetype,Running Style,Years Pro,Height,Weight,Birthdate,College
0,Rams,Aaron Donald,99,RE,29,82,90,99,86,99,...,99,"$101,892,000.00","$40,000,000.00",DE_PowerRusher,Default Stride Loose,6,73,280,5/23/1991,Pittsburgh
1,Patriots,Stephon Gilmore,99,CB,29,92,94,99,94,70,...,24,"$33,550,000.00","$31,450,000.00",CB_MantoMan,Default,8,73,202,9/19/1990,South Carolina
2,Panthers,Christian McCaffrey,99,HB,24,92,93,97,97,72,...,22,"$45,840,000.00","$32,190,000.00",HB_ReceivingBack,Short Stride Default,3,71,205,6/7/1996,Stanford
3,Chiefs,Patrick Mahomes,99,QB,24,81,87,97,88,69,...,15,"$6,840,000.00","$34,420,000.00",QB_Improviser,Default,3,75,230,9/17/1995,Texas Tech
4,Saints,Michael Thomas,99,WR,27,89,92,99,92,77,...,13,"$62,750,000.00","$35,130,000.00",WR_RouteRunner,Default,4,75,212,3/3/1993,Ohio State